// Generated by wxt
export {}
declare global {
  const { ChatOutlineIcon, ExternalLinkIcon, PromptIcon, QuickQuoteIcon }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/components/icons')
  const { ContentScriptContext }: typeof import('wxt/utils/content-script-context')
  const { EventBus, emit, emitSync, eventBus, eventNames, hasListeners, listenerCount, off, on, once, removeAllListeners }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/eventbus')
  const { InvalidMatchPattern, MatchPattern }: typeof import('wxt/utils/match-patterns')
  const { appendTextToEditor, clearEditor, createInputChangeListener, createModelStatusListener, getContentEditor, getDetailedButtonStatus, getEditorContent, getModelStatus, getSendButton, insertTextToEditor, isReadyToSend, isResponding, sendMessage, sendMessageAndWait, stopModelResponse, waitForModelResponse }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/editorUtils')
  const { browser }: typeof import('wxt/browser')
  const { createIframeUi }: typeof import('wxt/utils/content-script-ui/iframe')
  const { createIntegratedUi }: typeof import('wxt/utils/content-script-ui/integrated')
  const { createNewChatByClick, isInputReady }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/chatActions')
  const { createShadowRootUi }: typeof import('wxt/utils/content-script-ui/shadow-root')
  const { defineAppConfig }: typeof import('wxt/utils/define-app-config')
  const { defineBackground }: typeof import('wxt/utils/define-background')
  const { defineContentScript }: typeof import('wxt/utils/define-content-script')
  const { defineUnlistedScript }: typeof import('wxt/utils/define-unlisted-script')
  const { defineWxtPlugin }: typeof import('wxt/utils/define-wxt-plugin')
  const { extractModelResponseContent, extractUserQueryText, getAllChatWindows, getAllMessages, getAllModelMessages, getAllUserMessages, getChatSummary, getCurrentChatWindow, getDefaultChatWindow, hasChatHistory, isTemporaryChat }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/messageUtils')
  const { fakeBrowser }: typeof import('wxt/testing')
  const { getCurrentLocale, t }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/i18n')
  const { i18n }: typeof import('#i18n')
  const { injectScript }: typeof import('wxt/utils/inject-script')
  const { storage }: typeof import('wxt/utils/storage')
  const { useAppConfig }: typeof import('wxt/utils/app-config')
  const { useCallback, useContext, useEffect, useMemo, useReducer, useRef, useState }: typeof import('react')
  const { useEvent, useEventBus, useEventEmitter, useEventSubscriptions }: typeof import('/Users/ronktsang/projects/gemini-chrome-plugin/src/hooks/useEventBus')
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { EditorConfig, ModelStatus, ModelStatusCallback, InputChangeCallback, DetailedButtonStatus } from '/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/editorUtils'
  import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/editorUtils')
  // @ts-ignore
  export type { EventBus, EventCallback, EventMap, EventBusOptions } from '/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/eventbus'
  import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/eventbus')
  // @ts-ignore
  export type { MessageElement, UserMessage, ModelMessage, Message } from '/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/messageUtils'
  import('/Users/ronktsang/projects/gemini-chrome-plugin/src/utils/messageUtils')
}
