// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { i18n } from '#i18n';
  export { ChatOutlineIcon, QuickQuoteIcon, ExternalLinkIcon, PromptIcon } from '../src/components/icons';
  export { useEventBus, useEvent, useEventEmitter, useEventSubscriptions } from '../src/hooks/useEventBus';
  export { createNewChatByClick, isInputReady } from '../src/utils/chatActions';
  export { getContentEditor, getSendButton, isResponding, isReadyToSend, insertTextToEditor, appendTextToEditor, getEditorContent, clearEditor, sendMessage, stopModelResponse, getModelStatus, getDetailedButtonStatus, createModelStatusListener, createInputChangeListener, waitForModelResponse, sendMessageAndWait, EditorConfig, ModelStatus, ModelStatusCallback, InputChangeCallback, DetailedButtonStatus } from '../src/utils/editorUtils';
  export { EventBus, EventBus, eventBus, on, once, off, emit, emitSync, removeAllListeners, listenerCount, eventNames, hasListeners, EventCallback, EventMap, EventBusOptions } from '../src/utils/eventbus';
  export { t, getCurrentLocale } from '../src/utils/i18n';
  export { getAllUserMessages, getAllModelMessages, getAllMessages, getCurrentChatWindow, getAllChatWindows, getDefaultChatWindow, extractUserQueryText, extractModelResponseContent, hasChatHistory, getChatSummary, isTemporaryChat, MessageElement, UserMessage, ModelMessage, Message } from '../src/utils/messageUtils';
}
